version: "3.9"
   
services:
  web:
    image: 322502383001.dkr.ecr.sa-east-1.amazonaws.com/reset-challenge:latest
    command: python manage.py runserver 0.0.0.0:80
    environment:
      - SQS_QUEUE_URL=https://sqs.sa-east-1.amazonaws.com/322502383001/main-queue
      - EFS_SOURCE_FOLDER=/data/sourcefolder/
      - EFS_DESTINATION_FOLDER=/data/destinationfolder/
      - AWS_REGION=sa-east-1
    volumes:
      - .:/code2/
    ports:
      - "80:80"
    depends_on:
      - db
    x-aws-role:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action: sqs:*
          Resource: arn:aws:sqs:sa-east-1:322502383001:main-queue
volumes:
  efs-share: