# Generated by Django 3.1.2 on 2020-11-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('number', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('food_group', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.foodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MealOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ingredients', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('food', models.ManyToManyField(blank=True, to='Main.FoodPortion')),
                ('recipes', models.ManyToManyField(blank=True, to='Main.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('suggestions', models.TextField(blank=True, default='')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.meal')),
                ('meal_options', models.ManyToManyField(to='Main.MealOption')),
                ('recipes', models.ManyToManyField(to='Main.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MealUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.foodgroup')),
            ],
        ),
        migrations.AddField(
            model_name='mealoption',
            name='meal_units',
            field=models.ManyToManyField(to='Main.MealUnit'),
        ),
        migrations.AddField(
            model_name='foodportion',
            name='measurement',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.measurement'),
        ),
    ]
