# Generated by Django 3.1.2 on 2020-11-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleGroup',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('protocol', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.peoplegroup'),
        ),
    ]
