# Generated by Django 3.1.2 on 2020-11-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20201117_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('font_awesome_icon', models.CharField(default='', max_length=100)),
                ('background_color', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeTask',
            fields=[
                ('alltasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.alltasks')),
                ('title', models.CharField(default='', max_length=500)),
                ('text', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='')),
            ],
            bases=('Main.alltasks',),
        ),
        migrations.CreateModel(
            name='TextTask',
            fields=[
                ('alltasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.alltasks')),
                ('title', models.CharField(default='', max_length=500)),
                ('text', models.TextField(blank=True, default='')),
            ],
            bases=('Main.alltasks',),
        ),
        migrations.CreateModel(
            name='TaskLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.alltasks')),
            ],
        ),
    ]
