# Generated by Django 3.1.2 on 2020-11-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alltasks_challengetask_tasklines_texttask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskLines',
            new_name='TaskLine',
        ),
    ]
