# Generated by Django 3.1.2 on 2020-11-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20201124_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltasks',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='TaskLine',
        ),
    ]
