# Generated by Django 3.1.2 on 2020-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20201125_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetask',
            name='image',
            field=models.ImageField(upload_to='static/DB_images'),
        ),
    ]
