# Generated by Django 3.1.2 on 2020-11-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20201125_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyvote',
            name='people_group',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='surveyvote',
            name='question',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='food',
            field=models.ManyToManyField(blank=True, editable=False, to='Main.FoodPortion'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='recipes',
            field=models.ManyToManyField(blank=True, editable=False, to='Main.Recipe'),
        ),
    ]
