# Generated by Django 3.1.2 on 2020-11-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20201125_2257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyvote',
            unique_together=set(),
        ),
    ]
