# Generated by Django 3.1.2 on 2020-11-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20201125_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyvote',
            name='choice',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='surveyvote',
            name='people_group',
            field=models.CharField(max_length=5000),
        ),
    ]
