# Generated by Django 3.1.2 on 2020-11-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20201125_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltasks',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
