# Generated by Django 3.1.2 on 2020-11-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alltasks_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltasks',
            name='is_complete',
        ),
    ]
