# Generated by Django 3.1.2 on 2020-11-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_remove_alltasks_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplegroup',
            name='last_task_line',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, default=None, to='Main.AllTasks'),
        ),
        migrations.AlterField(
            model_name='multiplechoicesurveytask',
            name='choices',
            field=models.TextField(help_text='write the choices in different lines', max_length=5000),
        ),
    ]
