# Generated by Django 3.1.2 on 2020-11-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20201126_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alltasks',
            old_name='position',
            new_name='line_position',
        ),
    ]
