# Generated by Django 3.1.2 on 2020-11-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20201126_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationTask',
            fields=[
                ('alltasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.alltasks')),
                ('title', models.CharField(default='', max_length=500)),
                ('fields', models.TextField(help_text='write the fields in different lines', max_length=1000)),
                ('equations', models.TextField(help_text='write the equations in different lines', max_length=1000)),
                ('result_sentence', models.TextField(max_length=1000)),
            ],
            bases=('Main.alltasks',),
        ),
        migrations.CreateModel(
            name='WritingSurveyTask',
            fields=[
                ('alltasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.alltasks')),
                ('question', models.CharField(max_length=5000)),
            ],
            bases=('Main.alltasks',),
        ),
    ]
