# Generated by Django 3.1.2 on 2020-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_calculationtask_writingsurveytask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealunit',
            name='food_group',
        ),
        migrations.RemoveField(
            model_name='foodportion',
            name='food_group',
        ),
        migrations.RemoveField(
            model_name='protocolmeal',
            name='meal_options',
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='food_portions',
            field=models.ManyToManyField(to='Main.FoodPortion'),
        ),
        migrations.AddField(
            model_name='protocolmeal',
            name='food_groups',
            field=models.ManyToManyField(to='Main.FoodGroup'),
        ),
        migrations.AlterField(
            model_name='alltasks',
            name='line_position',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='calculationtask',
            name='result_sentence',
            field=models.TextField(help_text='write the sentence by using eq1, eq2, eq3... for the results of the equations.', max_length=1000),
        ),
        migrations.DeleteModel(
            name='MealOption',
        ),
        migrations.DeleteModel(
            name='MealUnit',
        ),
    ]
