# Generated by Django 3.1.2 on 2020-11-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20201128_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolmeal',
            name='food_groups',
        ),
        migrations.AlterField(
            model_name='alltasks',
            name='line_position',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
