# Generated by Django 3.1.2 on 2020-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20201130_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolmeal',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Every time you write 'group x' (group 1, group 2..), it will become a link"),
        ),
        migrations.AlterField(
            model_name='protocolmeal',
            name='meal',
            field=models.CharField(choices=[('Café-da-manhã', 'Café-da-manhã'), ('Lanche da manhã', 'Lanche da manhã'), ('Almoço', 'Almoço'), ('Lanche da tarde', 'Lanche da tarde'), ('Café da tarde', 'Café da tarde'), ('Jantar', 'Jantar'), ('Ceia', 'Ceia')], default='Almoço', max_length=20),
        ),
    ]
