# Generated by Django 3.1.2 on 2020-11-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20201130_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmeal',
            name='meal_oder',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
