# Generated by Django 3.1.2 on 2020-11-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_protocolmeal_meal_oder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolmeal',
            old_name='meal_oder',
            new_name='meal_order',
        ),
    ]
