# Generated by Django 3.1.2 on 2020-12-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_auto_20201130_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
